spring:
  config:
    activate:
      on-profile: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
---

spring:
  config:
    activate:
      on-profile: production
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
server:
  port: 8081
  tomcat:
    threads:
      max: 100
      min-spare: 10
    accept-count: 10000

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 8081
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accept-count: 10000
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
